import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        headline: ['Newsreader', 'Georgia', 'serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Advisor colors (dashboard)
        legal: '#3b82f6',
        health: '#10b981',
        finance: '#f59e0b',
        psychology: '#8b5cf6',
        home: '#f97316',
        // Dark theme (landing)
        'background': '#0e1320',
        'surface': '#0e1320',
        'surface-dim': '#0e1320',
        'surface-bright': '#343948',
        'surface-container-lowest': '#090e1b',
        'surface-container-low': '#161b29',
        'surface-container': '#1a1f2d',
        'surface-container-high': '#252a38',
        'surface-container-highest': '#303443',
        'surface-variant': '#303443',
        'on-surface': '#dee2f5',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#dee2f5',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'primary': '#adc6ff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'primary-container': '#4d8eff',
        'on-primary': '#002e6a',
        'on-primary-fixed': '#001a42',
        'on-primary-container': '#00285d',
        'on-primary-fixed-variant': '#004395',
        'inverse-primary': '#005ac2',
        'surface-tint': '#adc6ff',
        'secondary': '#4edea3',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'secondary-container': '#00a572',
        'on-secondary': '#003824',
        'on-secondary-fixed': '#002113',
        'on-secondary-container': '#00311f',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#d0bcff',
        'tertiary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#d0bcff',
        'tertiary-container': '#a078ff',
        'on-tertiary': '#3c0091',
        'on-tertiary-fixed': '#23005c',
        'on-tertiary-container': '#340080',
        'on-tertiary-fixed-variant': '#5516be',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dee2f5',
        'inverse-on-surface': '#2b303e',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideIn: { from: { transform: 'translateY(10px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
      },
    },
  },
  plugins: [],
};

export default config;
